sharp_snowflake_mart:
  target: devlocal
  outputs:
    devlocal:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #keypair config
      private_key_path: "{{ env_var('SFLK_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('SFLK_KEY_PASSPHRASE') }}" 

      #database config
      database: "{{ env_var('DBT_SFLK_MART_DB') }}"
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: "{{ env_var('DBT_SFLK_TRANS_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
    dev:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      password: "{{ env_var('SFLK_DBT_PW') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #database config
      database: "{{ env_var('DBT_SFLK_MART_DB') }}"
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: "{{ env_var('DBT_SFLK_TRANS_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
    tst:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      password: "{{ env_var('SFLK_DBT_PW') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #database config
      database: "{{ env_var('DBT_SFLK_MART_DB') }}"
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: "{{ env_var('DBT_SFLK_TRANS_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
    prd:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      password: "{{ env_var('SFLK_DBT_PW') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #database config
      database: "{{ env_var('DBT_SFLK_MART_DB') }}"
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: "{{ env_var('DBT_SFLK_TRANS_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
sharp_snowflake_dv:
  target: devlocal
  outputs:
    devlocal:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #keypair config
      private_key_path: "{{ env_var('SFLK_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('SFLK_KEY_PASSPHRASE') }}" 

      #database config
      database: DEV_LOAD_DB
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
    dev:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      password: "{{ env_var('SFLK_DBT_PW') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #database config
      database: DEV_LOAD_DB
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
    tst:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      password: "{{ env_var('SFLK_DBT_PW') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #database config
      database: TST_LOAD_DB
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
    prd:
      #connector config
      type: snowflake
      account: "{{ env_var('SFLK_ACCOUNT') }}"
      user: "{{ env_var('SFLK_DBT_USER') }}"
      password: "{{ env_var('SFLK_DBT_PW') }}"
      role: "{{ env_var('SFLK_DBT_ROLE') }}"

      #database config
      database: PRD_LOAD_DB
      warehouse: "{{ env_var('SFLK_DBT_WHSE') }}"
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
